#!/usr/bin/env bun
/**
 * Fetches gallery photos for the three new sections and writes them to
 * src/data/galleryExtras.ts. Run once; results are baked into the bundle.
 */
import { writeFile } from "fs/promises";

const UNSPLASH = process.env.UNSPLASH_ACCESS_KEY!;
const PEXELS = process.env.PEXELS_API_KEY!;
const PIXABAY = process.env.PIXABAY_API_KEY!;

type Photo = {
  src: string;
  alt: string;
  caption: string;
  credit: string;
  creditUrl: string;
  source: "Unsplash" | "Pexels" | "Pixabay";
};

async function fromUnsplash(query: string, count: number): Promise<Photo[]> {
  const r = await fetch(
    `https://api.unsplash.com/search/photos?query=${encodeURIComponent(query)}&per_page=${count}&orientation=landscape&content_filter=high`,
    { headers: { Authorization: `Client-ID ${UNSPLASH}` } },
  );
  if (!r.ok) return [];
  const j: any = await r.json();
  return (j.results ?? []).map((p: any) => ({
    src: p.urls.regular as string,
    alt: p.alt_description ?? query,
    caption: p.description ?? p.alt_description ?? query,
    credit: p.user.name as string,
    creditUrl: `${p.user.links.html}?utm_source=SlowBlues&utm_medium=referral`,
    source: "Unsplash" as const,
  }));
}

async function fromPexels(query: string, count: number): Promise<Photo[]> {
  const r = await fetch(
    `https://api.pexels.com/v1/search?query=${encodeURIComponent(query)}&per_page=${count}&orientation=landscape`,
    { headers: { Authorization: PEXELS } },
  );
  if (!r.ok) return [];
  const j: any = await r.json();
  return (j.photos ?? []).map((p: any) => ({
    src: p.src.large as string,
    alt: p.alt || query,
    caption: p.alt || query,
    credit: p.photographer as string,
    creditUrl: p.photographer_url as string,
    source: "Pexels" as const,
  }));
}

async function fromPixabay(query: string, count: number): Promise<Photo[]> {
  const r = await fetch(
    `https://pixabay.com/api/?key=${PIXABAY}&q=${encodeURIComponent(query)}&per_page=${Math.max(count, 3)}&image_type=photo&orientation=horizontal&safesearch=true`,
  );
  if (!r.ok) return [];
  const j: any = await r.json();
  return (j.hits ?? []).slice(0, count).map((h: any) => ({
    src: h.largeImageURL as string,
    alt: h.tags as string,
    caption: h.tags as string,
    credit: h.user as string,
    creditUrl: `https://pixabay.com/users/${encodeURIComponent(h.user)}-${h.user_id}/`,
    source: "Pixabay" as const,
  }));
}

async function gather(queries: string[], target: number): Promise<Photo[]> {
  const fetchers = [fromUnsplash, fromPexels, fromPixabay];
  const out: Photo[] = [];
  const seen = new Set<string>();
  for (const q of queries) {
    for (const f of fetchers) {
      if (out.length >= target) break;
      const batch = await f(q, target);
      for (const p of batch) {
        if (out.length >= target) break;
        if (!seen.has(p.src)) {
          seen.add(p.src);
          out.push(p);
        }
      }
    }
    if (out.length >= target) break;
  }
  return out.slice(0, target);
}

const sections = [
  {
    id: "electric-era",
    titleEn: "The Electric Era",
    leadEn: "From Chicago juke joints to amplified stages — the sound that changed everything.",
    queries: ["Chicago blues club vintage", "electric guitar blues stage", "blues musician microphone vintage"],
    count: 8,
  },
  {
    id: "guitars-and-gear",
    titleEn: "Blues Guitars & Gear",
    leadEn: "The instruments that gave the blues its voice.",
    queries: ["vintage electric guitar close up", "harmonica blues musician hands", "tube amplifier vintage music"],
    count: 6,
  },
  {
    id: "nordic-blues",
    titleEn: "Nordic Blues",
    leadEn: "The Scandinavian scene — festivals, clubs, and the long winter sound.",
    queries: ["Scandinavian concert blues festival", "nordic guitarist stage", "blues concert Norway Sweden"],
    count: 6,
  },
];

const result: any[] = [];
for (const s of sections) {
  console.log(`Fetching ${s.id}...`);
  const photos = await gather(s.queries, s.count);
  console.log(`  got ${photos.length}/${s.count}`);
  result.push({ ...s, photos });
}

const ts = `// Auto-generated by scripts/fetch_gallery_extras.ts. Do not edit by hand.
export type GalleryPhoto = {
  src: string;
  alt: string;
  caption: string;
  credit: string;
  creditUrl: string;
  source: "Unsplash" | "Pexels" | "Pixabay";
};

export type GallerySection = {
  id: string;
  titleEn: string;
  leadEn: string;
  photos: GalleryPhoto[];
};

export const GALLERY_EXTRAS: GallerySection[] = ${JSON.stringify(
  result.map((s) => ({ id: s.id, titleEn: s.titleEn, leadEn: s.leadEn, photos: s.photos })),
  null,
  2,
)};
`;

await writeFile("src/data/galleryExtras.ts", ts);
console.log("Wrote src/data/galleryExtras.ts");
