/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldmapRouteImport } from './routes/worldmap'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StylesRouteImport } from './routes/styles'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RadioRouteImport } from './routes/radio'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListenRouteImport } from './routes/listen'
import { Route as InstrumentsRouteImport } from './routes/instruments'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GuestbookRouteImport } from './routes/guestbook'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FestivalsRouteImport } from './routes/festivals'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizArchiveRouteImport } from './routes/quiz.archive'
import { Route as NewsletterTemplateRouteImport } from './routes/newsletter.template'
import { Route as NewsletterIdRouteImport } from './routes/newsletter.$id'
import { Route as LearnStylesRouteImport } from './routes/learn.styles'
import { Route as ExperienceMediaRouteImport } from './routes/experience.media'
import { Route as BlogIdRouteImport } from './routes/blog.$id'
import { Route as ArtistsSlugRouteImport } from './routes/artists.$slug'
import { Route as AboutMerchRouteImport } from './routes/about.merch'
import { Route as AboutGuestbookRouteImport } from './routes/about.guestbook'
import { Route as AboutBlogRouteImport } from './routes/about.blog'
import { Route as LocaleArtistsRouteImport } from './routes/$locale.artists'
import { Route as QuizCycleCycleRouteImport } from './routes/quiz.cycle.$cycle'
import { Route as AboutMerchSlugRouteImport } from './routes/about.merch.$slug'
import { Route as LocaleArtistsSlugRouteImport } from './routes/$locale.artists.$slug'
import { Route as AboutMerchCollectionSlugRouteImport } from './routes/about.merch.collection.$slug'

const WorldmapRoute = WorldmapRouteImport.update({
  id: '/worldmap',
  path: '/worldmap',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StylesRoute = StylesRouteImport.update({
  id: '/styles',
  path: '/styles',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioRoute = RadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListenRoute = ListenRouteImport.update({
  id: '/listen',
  path: '/listen',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrumentsRoute = InstrumentsRouteImport.update({
  id: '/instruments',
  path: '/instruments',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestbookRoute = GuestbookRouteImport.update({
  id: '/guestbook',
  path: '/guestbook',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalsRoute = FestivalsRouteImport.update({
  id: '/festivals',
  path: '/festivals',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizArchiveRoute = QuizArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => QuizRoute,
} as any)
const NewsletterTemplateRoute = NewsletterTemplateRouteImport.update({
  id: '/template',
  path: '/template',
  getParentRoute: () => NewsletterRoute,
} as any)
const NewsletterIdRoute = NewsletterIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NewsletterRoute,
} as any)
const LearnStylesRoute = LearnStylesRouteImport.update({
  id: '/learn/styles',
  path: '/learn/styles',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceMediaRoute = ExperienceMediaRouteImport.update({
  id: '/experience/media',
  path: '/experience/media',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BlogRoute,
} as any)
const ArtistsSlugRoute = ArtistsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArtistsRoute,
} as any)
const AboutMerchRoute = AboutMerchRouteImport.update({
  id: '/about/merch',
  path: '/about/merch',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutGuestbookRoute = AboutGuestbookRouteImport.update({
  id: '/about/guestbook',
  path: '/about/guestbook',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutBlogRoute = AboutBlogRouteImport.update({
  id: '/about/blog',
  path: '/about/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleArtistsRoute = LocaleArtistsRouteImport.update({
  id: '/$locale/artists',
  path: '/$locale/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizCycleCycleRoute = QuizCycleCycleRouteImport.update({
  id: '/cycle/$cycle',
  path: '/cycle/$cycle',
  getParentRoute: () => QuizRoute,
} as any)
const AboutMerchSlugRoute = AboutMerchSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AboutMerchRoute,
} as any)
const LocaleArtistsSlugRoute = LocaleArtistsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocaleArtistsRoute,
} as any)
const AboutMerchCollectionSlugRoute =
  AboutMerchCollectionSlugRouteImport.update({
    id: '/collection/$slug',
    path: '/collection/$slug',
    getParentRoute: () => AboutMerchRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/festivals': typeof FestivalsRoute
  '/gallery': typeof GalleryRoute
  '/guestbook': typeof GuestbookRoute
  '/history': typeof HistoryRoute
  '/instruments': typeof InstrumentsRoute
  '/listen': typeof ListenRoute
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRouteWithChildren
  '/radio': typeof RadioRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/styles': typeof StylesRoute
  '/support': typeof SupportRoute
  '/updates': typeof UpdatesRoute
  '/watch': typeof WatchRoute
  '/worldmap': typeof WorldmapRoute
  '/$locale/artists': typeof LocaleArtistsRouteWithChildren
  '/about/blog': typeof AboutBlogRoute
  '/about/guestbook': typeof AboutGuestbookRoute
  '/about/merch': typeof AboutMerchRouteWithChildren
  '/artists/$slug': typeof ArtistsSlugRoute
  '/blog/$id': typeof BlogIdRoute
  '/experience/media': typeof ExperienceMediaRoute
  '/learn/styles': typeof LearnStylesRoute
  '/newsletter/$id': typeof NewsletterIdRoute
  '/newsletter/template': typeof NewsletterTemplateRoute
  '/quiz/archive': typeof QuizArchiveRoute
  '/$locale/artists/$slug': typeof LocaleArtistsSlugRoute
  '/about/merch/$slug': typeof AboutMerchSlugRoute
  '/quiz/cycle/$cycle': typeof QuizCycleCycleRoute
  '/about/merch/collection/$slug': typeof AboutMerchCollectionSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/festivals': typeof FestivalsRoute
  '/gallery': typeof GalleryRoute
  '/guestbook': typeof GuestbookRoute
  '/history': typeof HistoryRoute
  '/instruments': typeof InstrumentsRoute
  '/listen': typeof ListenRoute
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRouteWithChildren
  '/radio': typeof RadioRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/styles': typeof StylesRoute
  '/support': typeof SupportRoute
  '/updates': typeof UpdatesRoute
  '/watch': typeof WatchRoute
  '/worldmap': typeof WorldmapRoute
  '/$locale/artists': typeof LocaleArtistsRouteWithChildren
  '/about/blog': typeof AboutBlogRoute
  '/about/guestbook': typeof AboutGuestbookRoute
  '/about/merch': typeof AboutMerchRouteWithChildren
  '/artists/$slug': typeof ArtistsSlugRoute
  '/blog/$id': typeof BlogIdRoute
  '/experience/media': typeof ExperienceMediaRoute
  '/learn/styles': typeof LearnStylesRoute
  '/newsletter/$id': typeof NewsletterIdRoute
  '/newsletter/template': typeof NewsletterTemplateRoute
  '/quiz/archive': typeof QuizArchiveRoute
  '/$locale/artists/$slug': typeof LocaleArtistsSlugRoute
  '/about/merch/$slug': typeof AboutMerchSlugRoute
  '/quiz/cycle/$cycle': typeof QuizCycleCycleRoute
  '/about/merch/collection/$slug': typeof AboutMerchCollectionSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/festivals': typeof FestivalsRoute
  '/gallery': typeof GalleryRoute
  '/guestbook': typeof GuestbookRoute
  '/history': typeof HistoryRoute
  '/instruments': typeof InstrumentsRoute
  '/listen': typeof ListenRoute
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRouteWithChildren
  '/radio': typeof RadioRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/styles': typeof StylesRoute
  '/support': typeof SupportRoute
  '/updates': typeof UpdatesRoute
  '/watch': typeof WatchRoute
  '/worldmap': typeof WorldmapRoute
  '/$locale/artists': typeof LocaleArtistsRouteWithChildren
  '/about/blog': typeof AboutBlogRoute
  '/about/guestbook': typeof AboutGuestbookRoute
  '/about/merch': typeof AboutMerchRouteWithChildren
  '/artists/$slug': typeof ArtistsSlugRoute
  '/blog/$id': typeof BlogIdRoute
  '/experience/media': typeof ExperienceMediaRoute
  '/learn/styles': typeof LearnStylesRoute
  '/newsletter/$id': typeof NewsletterIdRoute
  '/newsletter/template': typeof NewsletterTemplateRoute
  '/quiz/archive': typeof QuizArchiveRoute
  '/$locale/artists/$slug': typeof LocaleArtistsSlugRoute
  '/about/merch/$slug': typeof AboutMerchSlugRoute
  '/quiz/cycle/$cycle': typeof QuizCycleCycleRoute
  '/about/merch/collection/$slug': typeof AboutMerchCollectionSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/artists'
    | '/blog'
    | '/compare'
    | '/contact'
    | '/festivals'
    | '/gallery'
    | '/guestbook'
    | '/history'
    | '/instruments'
    | '/listen'
    | '/login'
    | '/newsletter'
    | '/privacy'
    | '/quiz'
    | '/radio'
    | '/reviews'
    | '/sitemap.xml'
    | '/styles'
    | '/support'
    | '/updates'
    | '/watch'
    | '/worldmap'
    | '/$locale/artists'
    | '/about/blog'
    | '/about/guestbook'
    | '/about/merch'
    | '/artists/$slug'
    | '/blog/$id'
    | '/experience/media'
    | '/learn/styles'
    | '/newsletter/$id'
    | '/newsletter/template'
    | '/quiz/archive'
    | '/$locale/artists/$slug'
    | '/about/merch/$slug'
    | '/quiz/cycle/$cycle'
    | '/about/merch/collection/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/artists'
    | '/blog'
    | '/compare'
    | '/contact'
    | '/festivals'
    | '/gallery'
    | '/guestbook'
    | '/history'
    | '/instruments'
    | '/listen'
    | '/login'
    | '/newsletter'
    | '/privacy'
    | '/quiz'
    | '/radio'
    | '/reviews'
    | '/sitemap.xml'
    | '/styles'
    | '/support'
    | '/updates'
    | '/watch'
    | '/worldmap'
    | '/$locale/artists'
    | '/about/blog'
    | '/about/guestbook'
    | '/about/merch'
    | '/artists/$slug'
    | '/blog/$id'
    | '/experience/media'
    | '/learn/styles'
    | '/newsletter/$id'
    | '/newsletter/template'
    | '/quiz/archive'
    | '/$locale/artists/$slug'
    | '/about/merch/$slug'
    | '/quiz/cycle/$cycle'
    | '/about/merch/collection/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/artists'
    | '/blog'
    | '/compare'
    | '/contact'
    | '/festivals'
    | '/gallery'
    | '/guestbook'
    | '/history'
    | '/instruments'
    | '/listen'
    | '/login'
    | '/newsletter'
    | '/privacy'
    | '/quiz'
    | '/radio'
    | '/reviews'
    | '/sitemap.xml'
    | '/styles'
    | '/support'
    | '/updates'
    | '/watch'
    | '/worldmap'
    | '/$locale/artists'
    | '/about/blog'
    | '/about/guestbook'
    | '/about/merch'
    | '/artists/$slug'
    | '/blog/$id'
    | '/experience/media'
    | '/learn/styles'
    | '/newsletter/$id'
    | '/newsletter/template'
    | '/quiz/archive'
    | '/$locale/artists/$slug'
    | '/about/merch/$slug'
    | '/quiz/cycle/$cycle'
    | '/about/merch/collection/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArtistsRoute: typeof ArtistsRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  FestivalsRoute: typeof FestivalsRoute
  GalleryRoute: typeof GalleryRoute
  GuestbookRoute: typeof GuestbookRoute
  HistoryRoute: typeof HistoryRoute
  InstrumentsRoute: typeof InstrumentsRoute
  ListenRoute: typeof ListenRoute
  LoginRoute: typeof LoginRoute
  NewsletterRoute: typeof NewsletterRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  QuizRoute: typeof QuizRouteWithChildren
  RadioRoute: typeof RadioRoute
  ReviewsRoute: typeof ReviewsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StylesRoute: typeof StylesRoute
  SupportRoute: typeof SupportRoute
  UpdatesRoute: typeof UpdatesRoute
  WatchRoute: typeof WatchRoute
  WorldmapRoute: typeof WorldmapRoute
  LocaleArtistsRoute: typeof LocaleArtistsRouteWithChildren
  AboutBlogRoute: typeof AboutBlogRoute
  AboutGuestbookRoute: typeof AboutGuestbookRoute
  AboutMerchRoute: typeof AboutMerchRouteWithChildren
  ExperienceMediaRoute: typeof ExperienceMediaRoute
  LearnStylesRoute: typeof LearnStylesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worldmap': {
      id: '/worldmap'
      path: '/worldmap'
      fullPath: '/worldmap'
      preLoaderRoute: typeof WorldmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styles': {
      id: '/styles'
      path: '/styles'
      fullPath: '/styles'
      preLoaderRoute: typeof StylesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio': {
      id: '/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listen': {
      id: '/listen'
      path: '/listen'
      fullPath: '/listen'
      preLoaderRoute: typeof ListenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instruments': {
      id: '/instruments'
      path: '/instruments'
      fullPath: '/instruments'
      preLoaderRoute: typeof InstrumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guestbook': {
      id: '/guestbook'
      path: '/guestbook'
      fullPath: '/guestbook'
      preLoaderRoute: typeof GuestbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festivals': {
      id: '/festivals'
      path: '/festivals'
      fullPath: '/festivals'
      preLoaderRoute: typeof FestivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/archive': {
      id: '/quiz/archive'
      path: '/archive'
      fullPath: '/quiz/archive'
      preLoaderRoute: typeof QuizArchiveRouteImport
      parentRoute: typeof QuizRoute
    }
    '/newsletter/template': {
      id: '/newsletter/template'
      path: '/template'
      fullPath: '/newsletter/template'
      preLoaderRoute: typeof NewsletterTemplateRouteImport
      parentRoute: typeof NewsletterRoute
    }
    '/newsletter/$id': {
      id: '/newsletter/$id'
      path: '/$id'
      fullPath: '/newsletter/$id'
      preLoaderRoute: typeof NewsletterIdRouteImport
      parentRoute: typeof NewsletterRoute
    }
    '/learn/styles': {
      id: '/learn/styles'
      path: '/learn/styles'
      fullPath: '/learn/styles'
      preLoaderRoute: typeof LearnStylesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/media': {
      id: '/experience/media'
      path: '/experience/media'
      fullPath: '/experience/media'
      preLoaderRoute: typeof ExperienceMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof BlogRoute
    }
    '/artists/$slug': {
      id: '/artists/$slug'
      path: '/$slug'
      fullPath: '/artists/$slug'
      preLoaderRoute: typeof ArtistsSlugRouteImport
      parentRoute: typeof ArtistsRoute
    }
    '/about/merch': {
      id: '/about/merch'
      path: '/about/merch'
      fullPath: '/about/merch'
      preLoaderRoute: typeof AboutMerchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/guestbook': {
      id: '/about/guestbook'
      path: '/about/guestbook'
      fullPath: '/about/guestbook'
      preLoaderRoute: typeof AboutGuestbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/blog': {
      id: '/about/blog'
      path: '/about/blog'
      fullPath: '/about/blog'
      preLoaderRoute: typeof AboutBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/artists': {
      id: '/$locale/artists'
      path: '/$locale/artists'
      fullPath: '/$locale/artists'
      preLoaderRoute: typeof LocaleArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/cycle/$cycle': {
      id: '/quiz/cycle/$cycle'
      path: '/cycle/$cycle'
      fullPath: '/quiz/cycle/$cycle'
      preLoaderRoute: typeof QuizCycleCycleRouteImport
      parentRoute: typeof QuizRoute
    }
    '/about/merch/$slug': {
      id: '/about/merch/$slug'
      path: '/$slug'
      fullPath: '/about/merch/$slug'
      preLoaderRoute: typeof AboutMerchSlugRouteImport
      parentRoute: typeof AboutMerchRoute
    }
    '/$locale/artists/$slug': {
      id: '/$locale/artists/$slug'
      path: '/$slug'
      fullPath: '/$locale/artists/$slug'
      preLoaderRoute: typeof LocaleArtistsSlugRouteImport
      parentRoute: typeof LocaleArtistsRoute
    }
    '/about/merch/collection/$slug': {
      id: '/about/merch/collection/$slug'
      path: '/collection/$slug'
      fullPath: '/about/merch/collection/$slug'
      preLoaderRoute: typeof AboutMerchCollectionSlugRouteImport
      parentRoute: typeof AboutMerchRoute
    }
  }
}

interface ArtistsRouteChildren {
  ArtistsSlugRoute: typeof ArtistsSlugRoute
}

const ArtistsRouteChildren: ArtistsRouteChildren = {
  ArtistsSlugRoute: ArtistsSlugRoute,
}

const ArtistsRouteWithChildren =
  ArtistsRoute._addFileChildren(ArtistsRouteChildren)

interface BlogRouteChildren {
  BlogIdRoute: typeof BlogIdRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogIdRoute: BlogIdRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface NewsletterRouteChildren {
  NewsletterIdRoute: typeof NewsletterIdRoute
  NewsletterTemplateRoute: typeof NewsletterTemplateRoute
}

const NewsletterRouteChildren: NewsletterRouteChildren = {
  NewsletterIdRoute: NewsletterIdRoute,
  NewsletterTemplateRoute: NewsletterTemplateRoute,
}

const NewsletterRouteWithChildren = NewsletterRoute._addFileChildren(
  NewsletterRouteChildren,
)

interface QuizRouteChildren {
  QuizArchiveRoute: typeof QuizArchiveRoute
  QuizCycleCycleRoute: typeof QuizCycleCycleRoute
}

const QuizRouteChildren: QuizRouteChildren = {
  QuizArchiveRoute: QuizArchiveRoute,
  QuizCycleCycleRoute: QuizCycleCycleRoute,
}

const QuizRouteWithChildren = QuizRoute._addFileChildren(QuizRouteChildren)

interface LocaleArtistsRouteChildren {
  LocaleArtistsSlugRoute: typeof LocaleArtistsSlugRoute
}

const LocaleArtistsRouteChildren: LocaleArtistsRouteChildren = {
  LocaleArtistsSlugRoute: LocaleArtistsSlugRoute,
}

const LocaleArtistsRouteWithChildren = LocaleArtistsRoute._addFileChildren(
  LocaleArtistsRouteChildren,
)

interface AboutMerchRouteChildren {
  AboutMerchSlugRoute: typeof AboutMerchSlugRoute
  AboutMerchCollectionSlugRoute: typeof AboutMerchCollectionSlugRoute
}

const AboutMerchRouteChildren: AboutMerchRouteChildren = {
  AboutMerchSlugRoute: AboutMerchSlugRoute,
  AboutMerchCollectionSlugRoute: AboutMerchCollectionSlugRoute,
}

const AboutMerchRouteWithChildren = AboutMerchRoute._addFileChildren(
  AboutMerchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArtistsRoute: ArtistsRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  FestivalsRoute: FestivalsRoute,
  GalleryRoute: GalleryRoute,
  GuestbookRoute: GuestbookRoute,
  HistoryRoute: HistoryRoute,
  InstrumentsRoute: InstrumentsRoute,
  ListenRoute: ListenRoute,
  LoginRoute: LoginRoute,
  NewsletterRoute: NewsletterRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  QuizRoute: QuizRouteWithChildren,
  RadioRoute: RadioRoute,
  ReviewsRoute: ReviewsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StylesRoute: StylesRoute,
  SupportRoute: SupportRoute,
  UpdatesRoute: UpdatesRoute,
  WatchRoute: WatchRoute,
  WorldmapRoute: WorldmapRoute,
  LocaleArtistsRoute: LocaleArtistsRouteWithChildren,
  AboutBlogRoute: AboutBlogRoute,
  AboutGuestbookRoute: AboutGuestbookRoute,
  AboutMerchRoute: AboutMerchRouteWithChildren,
  ExperienceMediaRoute: ExperienceMediaRoute,
  LearnStylesRoute: LearnStylesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
