/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldmapRouteImport } from './routes/worldmap'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StylesRouteImport } from './routes/styles'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RadioRouteImport } from './routes/radio'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListenRouteImport } from './routes/listen'
import { Route as InstrumentsRouteImport } from './routes/instruments'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GuestbookRouteImport } from './routes/guestbook'
import { Route as GdprRouteImport } from './routes/gdpr'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FestivalsRouteImport } from './routes/festivals'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as CopyrightRouteImport } from './routes/copyright'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewsIndexRouteImport } from './routes/reviews.index'
import { Route as QuizIndexRouteImport } from './routes/quiz.index'
import { Route as NewsletterIndexRouteImport } from './routes/newsletter.index'
import { Route as ConcertsIndexRouteImport } from './routes/concerts.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ArtistsIndexRouteImport } from './routes/artists.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as ReviewsSlugRouteImport } from './routes/reviews.$slug'
import { Route as QuizArchiveRouteImport } from './routes/quiz.archive'
import { Route as NewsletterTemplateRouteImport } from './routes/newsletter.template'
import { Route as NewsletterIdRouteImport } from './routes/newsletter.$id'
import { Route as LearnStylesRouteImport } from './routes/learn.styles'
import { Route as LearnGearRouteImport } from './routes/learn.gear'
import { Route as ExperienceMediaRouteImport } from './routes/experience.media'
import { Route as EditorialImagesRouteImport } from './routes/editorial.images'
import { Route as ConcertsSlugRouteImport } from './routes/concerts.$slug'
import { Route as BlogIdRouteImport } from './routes/blog.$id'
import { Route as ArtistsSlugRouteImport } from './routes/artists.$slug'
import { Route as AdminWikidataRouteImport } from './routes/admin.wikidata'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminQuotesRouteImport } from './routes/admin.quotes'
import { Route as AdminQualityRouteImport } from './routes/admin.quality'
import { Route as AdminLinksRouteImport } from './routes/admin.links'
import { Route as AdminArtistsRouteImport } from './routes/admin.artists'
import { Route as AboutMerchRouteImport } from './routes/about.merch'
import { Route as AboutGuestbookRouteImport } from './routes/about.guestbook'
import { Route as AboutBlogRouteImport } from './routes/about.blog'
import { Route as AboutAdvertiseRouteImport } from './routes/about.advertise'
import { Route as LocaleArtistsIndexRouteImport } from './routes/$locale.artists.index'
import { Route as QuizCycleCycleRouteImport } from './routes/quiz.cycle.$cycle'
import { Route as ApiPublicFourthwallWebhookRouteImport } from './routes/api/public/fourthwall-webhook'
import { Route as AdminArtistsSlugRouteImport } from './routes/admin.artists.$slug'
import { Route as AboutMerchSlugRouteImport } from './routes/about.merch.$slug'
import { Route as LocaleArtistsSlugRouteImport } from './routes/$locale.artists.$slug'
import { Route as LocaleAboutAdvertiseRouteImport } from './routes/$locale.about.advertise'
import { Route as AboutMerchCollectionSlugRouteImport } from './routes/about.merch.collection.$slug'

const WorldmapRoute = WorldmapRouteImport.update({
  id: '/worldmap',
  path: '/worldmap',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StylesRoute = StylesRouteImport.update({
  id: '/styles',
  path: '/styles',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioRoute = RadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListenRoute = ListenRouteImport.update({
  id: '/listen',
  path: '/listen',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrumentsRoute = InstrumentsRouteImport.update({
  id: '/instruments',
  path: '/instruments',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestbookRoute = GuestbookRouteImport.update({
  id: '/guestbook',
  path: '/guestbook',
  getParentRoute: () => rootRouteImport,
} as any)
const GdprRoute = GdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalsRoute = FestivalsRouteImport.update({
  id: '/festivals',
  path: '/festivals',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyrightRoute = CopyrightRouteImport.update({
  id: '/copyright',
  path: '/copyright',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsIndexRoute = ReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIndexRoute = QuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterIndexRoute = NewsletterIndexRouteImport.update({
  id: '/newsletter/',
  path: '/newsletter/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcertsIndexRoute = ConcertsIndexRouteImport.update({
  id: '/concerts/',
  path: '/concerts/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsIndexRoute = ArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsSlugRoute = ReviewsSlugRouteImport.update({
  id: '/reviews/$slug',
  path: '/reviews/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizArchiveRoute = QuizArchiveRouteImport.update({
  id: '/quiz/archive',
  path: '/quiz/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterTemplateRoute = NewsletterTemplateRouteImport.update({
  id: '/newsletter/template',
  path: '/newsletter/template',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterIdRoute = NewsletterIdRouteImport.update({
  id: '/newsletter/$id',
  path: '/newsletter/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnStylesRoute = LearnStylesRouteImport.update({
  id: '/learn/styles',
  path: '/learn/styles',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnGearRoute = LearnGearRouteImport.update({
  id: '/learn/gear',
  path: '/learn/gear',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceMediaRoute = ExperienceMediaRouteImport.update({
  id: '/experience/media',
  path: '/experience/media',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialImagesRoute = EditorialImagesRouteImport.update({
  id: '/editorial/images',
  path: '/editorial/images',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcertsSlugRoute = ConcertsSlugRouteImport.update({
  id: '/concerts/$slug',
  path: '/concerts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsSlugRoute = ArtistsSlugRouteImport.update({
  id: '/artists/$slug',
  path: '/artists/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWikidataRoute = AdminWikidataRouteImport.update({
  id: '/admin/wikidata',
  path: '/admin/wikidata',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuotesRoute = AdminQuotesRouteImport.update({
  id: '/admin/quotes',
  path: '/admin/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQualityRoute = AdminQualityRouteImport.update({
  id: '/admin/quality',
  path: '/admin/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLinksRoute = AdminLinksRouteImport.update({
  id: '/admin/links',
  path: '/admin/links',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArtistsRoute = AdminArtistsRouteImport.update({
  id: '/admin/artists',
  path: '/admin/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMerchRoute = AboutMerchRouteImport.update({
  id: '/about/merch',
  path: '/about/merch',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutGuestbookRoute = AboutGuestbookRouteImport.update({
  id: '/about/guestbook',
  path: '/about/guestbook',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutBlogRoute = AboutBlogRouteImport.update({
  id: '/about/blog',
  path: '/about/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutAdvertiseRoute = AboutAdvertiseRouteImport.update({
  id: '/about/advertise',
  path: '/about/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleArtistsIndexRoute = LocaleArtistsIndexRouteImport.update({
  id: '/$locale/artists/',
  path: '/$locale/artists/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizCycleCycleRoute = QuizCycleCycleRouteImport.update({
  id: '/quiz/cycle/$cycle',
  path: '/quiz/cycle/$cycle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFourthwallWebhookRoute =
  ApiPublicFourthwallWebhookRouteImport.update({
    id: '/api/public/fourthwall-webhook',
    path: '/api/public/fourthwall-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminArtistsSlugRoute = AdminArtistsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminArtistsRoute,
} as any)
const AboutMerchSlugRoute = AboutMerchSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AboutMerchRoute,
} as any)
const LocaleArtistsSlugRoute = LocaleArtistsSlugRouteImport.update({
  id: '/$locale/artists/$slug',
  path: '/$locale/artists/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleAboutAdvertiseRoute = LocaleAboutAdvertiseRouteImport.update({
  id: '/$locale/about/advertise',
  path: '/$locale/about/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMerchCollectionSlugRoute =
  AboutMerchCollectionSlugRouteImport.update({
    id: '/collection/$slug',
    path: '/collection/$slug',
    getParentRoute: () => AboutMerchRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/copyright': typeof CopyrightRoute
  '/disclaimer': typeof DisclaimerRoute
  '/festivals': typeof FestivalsRoute
  '/gallery': typeof GalleryRoute
  '/gdpr': typeof GdprRoute
  '/guestbook': typeof GuestbookRoute
  '/history': typeof HistoryRoute
  '/instruments': typeof InstrumentsRoute
  '/listen': typeof ListenRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/radio': typeof RadioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/styles': typeof StylesRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/updates': typeof UpdatesRoute
  '/watch': typeof WatchRoute
  '/worldmap': typeof WorldmapRoute
  '/about/advertise': typeof AboutAdvertiseRoute
  '/about/blog': typeof AboutBlogRoute
  '/about/guestbook': typeof AboutGuestbookRoute
  '/about/merch': typeof AboutMerchRouteWithChildren
  '/admin/artists': typeof AdminArtistsRouteWithChildren
  '/admin/links': typeof AdminLinksRoute
  '/admin/quality': typeof AdminQualityRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/wikidata': typeof AdminWikidataRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/blog/$id': typeof BlogIdRoute
  '/concerts/$slug': typeof ConcertsSlugRoute
  '/editorial/images': typeof EditorialImagesRoute
  '/experience/media': typeof ExperienceMediaRoute
  '/learn/gear': typeof LearnGearRoute
  '/learn/styles': typeof LearnStylesRoute
  '/newsletter/$id': typeof NewsletterIdRoute
  '/newsletter/template': typeof NewsletterTemplateRoute
  '/quiz/archive': typeof QuizArchiveRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/artists/': typeof ArtistsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/concerts/': typeof ConcertsIndexRoute
  '/newsletter/': typeof NewsletterIndexRoute
  '/quiz/': typeof QuizIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
  '/$locale/about/advertise': typeof LocaleAboutAdvertiseRoute
  '/$locale/artists/$slug': typeof LocaleArtistsSlugRoute
  '/about/merch/$slug': typeof AboutMerchSlugRoute
  '/admin/artists/$slug': typeof AdminArtistsSlugRoute
  '/api/public/fourthwall-webhook': typeof ApiPublicFourthwallWebhookRoute
  '/quiz/cycle/$cycle': typeof QuizCycleCycleRoute
  '/$locale/artists/': typeof LocaleArtistsIndexRoute
  '/about/merch/collection/$slug': typeof AboutMerchCollectionSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/copyright': typeof CopyrightRoute
  '/disclaimer': typeof DisclaimerRoute
  '/festivals': typeof FestivalsRoute
  '/gallery': typeof GalleryRoute
  '/gdpr': typeof GdprRoute
  '/guestbook': typeof GuestbookRoute
  '/history': typeof HistoryRoute
  '/instruments': typeof InstrumentsRoute
  '/listen': typeof ListenRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/radio': typeof RadioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/styles': typeof StylesRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/updates': typeof UpdatesRoute
  '/watch': typeof WatchRoute
  '/worldmap': typeof WorldmapRoute
  '/about/advertise': typeof AboutAdvertiseRoute
  '/about/blog': typeof AboutBlogRoute
  '/about/guestbook': typeof AboutGuestbookRoute
  '/about/merch': typeof AboutMerchRouteWithChildren
  '/admin/artists': typeof AdminArtistsRouteWithChildren
  '/admin/links': typeof AdminLinksRoute
  '/admin/quality': typeof AdminQualityRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/wikidata': typeof AdminWikidataRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/blog/$id': typeof BlogIdRoute
  '/concerts/$slug': typeof ConcertsSlugRoute
  '/editorial/images': typeof EditorialImagesRoute
  '/experience/media': typeof ExperienceMediaRoute
  '/learn/gear': typeof LearnGearRoute
  '/learn/styles': typeof LearnStylesRoute
  '/newsletter/$id': typeof NewsletterIdRoute
  '/newsletter/template': typeof NewsletterTemplateRoute
  '/quiz/archive': typeof QuizArchiveRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
  '/about': typeof AboutIndexRoute
  '/admin': typeof AdminIndexRoute
  '/artists': typeof ArtistsIndexRoute
  '/blog': typeof BlogIndexRoute
  '/concerts': typeof ConcertsIndexRoute
  '/newsletter': typeof NewsletterIndexRoute
  '/quiz': typeof QuizIndexRoute
  '/reviews': typeof ReviewsIndexRoute
  '/$locale/about/advertise': typeof LocaleAboutAdvertiseRoute
  '/$locale/artists/$slug': typeof LocaleArtistsSlugRoute
  '/about/merch/$slug': typeof AboutMerchSlugRoute
  '/admin/artists/$slug': typeof AdminArtistsSlugRoute
  '/api/public/fourthwall-webhook': typeof ApiPublicFourthwallWebhookRoute
  '/quiz/cycle/$cycle': typeof QuizCycleCycleRoute
  '/$locale/artists': typeof LocaleArtistsIndexRoute
  '/about/merch/collection/$slug': typeof AboutMerchCollectionSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/copyright': typeof CopyrightRoute
  '/disclaimer': typeof DisclaimerRoute
  '/festivals': typeof FestivalsRoute
  '/gallery': typeof GalleryRoute
  '/gdpr': typeof GdprRoute
  '/guestbook': typeof GuestbookRoute
  '/history': typeof HistoryRoute
  '/instruments': typeof InstrumentsRoute
  '/listen': typeof ListenRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/radio': typeof RadioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/styles': typeof StylesRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/updates': typeof UpdatesRoute
  '/watch': typeof WatchRoute
  '/worldmap': typeof WorldmapRoute
  '/about/advertise': typeof AboutAdvertiseRoute
  '/about/blog': typeof AboutBlogRoute
  '/about/guestbook': typeof AboutGuestbookRoute
  '/about/merch': typeof AboutMerchRouteWithChildren
  '/admin/artists': typeof AdminArtistsRouteWithChildren
  '/admin/links': typeof AdminLinksRoute
  '/admin/quality': typeof AdminQualityRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/wikidata': typeof AdminWikidataRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/blog/$id': typeof BlogIdRoute
  '/concerts/$slug': typeof ConcertsSlugRoute
  '/editorial/images': typeof EditorialImagesRoute
  '/experience/media': typeof ExperienceMediaRoute
  '/learn/gear': typeof LearnGearRoute
  '/learn/styles': typeof LearnStylesRoute
  '/newsletter/$id': typeof NewsletterIdRoute
  '/newsletter/template': typeof NewsletterTemplateRoute
  '/quiz/archive': typeof QuizArchiveRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/artists/': typeof ArtistsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/concerts/': typeof ConcertsIndexRoute
  '/newsletter/': typeof NewsletterIndexRoute
  '/quiz/': typeof QuizIndexRoute
  '/reviews/': typeof ReviewsIndexRoute
  '/$locale/about/advertise': typeof LocaleAboutAdvertiseRoute
  '/$locale/artists/$slug': typeof LocaleArtistsSlugRoute
  '/about/merch/$slug': typeof AboutMerchSlugRoute
  '/admin/artists/$slug': typeof AdminArtistsSlugRoute
  '/api/public/fourthwall-webhook': typeof ApiPublicFourthwallWebhookRoute
  '/quiz/cycle/$cycle': typeof QuizCycleCycleRoute
  '/$locale/artists/': typeof LocaleArtistsIndexRoute
  '/about/merch/collection/$slug': typeof AboutMerchCollectionSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/compare'
    | '/contact'
    | '/cookies'
    | '/copyright'
    | '/disclaimer'
    | '/festivals'
    | '/gallery'
    | '/gdpr'
    | '/guestbook'
    | '/history'
    | '/instruments'
    | '/listen'
    | '/login'
    | '/privacy'
    | '/radio'
    | '/sitemap.xml'
    | '/styles'
    | '/support'
    | '/terms'
    | '/updates'
    | '/watch'
    | '/worldmap'
    | '/about/advertise'
    | '/about/blog'
    | '/about/guestbook'
    | '/about/merch'
    | '/admin/artists'
    | '/admin/links'
    | '/admin/quality'
    | '/admin/quotes'
    | '/admin/reviews'
    | '/admin/wikidata'
    | '/artists/$slug'
    | '/blog/$id'
    | '/concerts/$slug'
    | '/editorial/images'
    | '/experience/media'
    | '/learn/gear'
    | '/learn/styles'
    | '/newsletter/$id'
    | '/newsletter/template'
    | '/quiz/archive'
    | '/reviews/$slug'
    | '/about/'
    | '/admin/'
    | '/artists/'
    | '/blog/'
    | '/concerts/'
    | '/newsletter/'
    | '/quiz/'
    | '/reviews/'
    | '/$locale/about/advertise'
    | '/$locale/artists/$slug'
    | '/about/merch/$slug'
    | '/admin/artists/$slug'
    | '/api/public/fourthwall-webhook'
    | '/quiz/cycle/$cycle'
    | '/$locale/artists/'
    | '/about/merch/collection/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/compare'
    | '/contact'
    | '/cookies'
    | '/copyright'
    | '/disclaimer'
    | '/festivals'
    | '/gallery'
    | '/gdpr'
    | '/guestbook'
    | '/history'
    | '/instruments'
    | '/listen'
    | '/login'
    | '/privacy'
    | '/radio'
    | '/sitemap.xml'
    | '/styles'
    | '/support'
    | '/terms'
    | '/updates'
    | '/watch'
    | '/worldmap'
    | '/about/advertise'
    | '/about/blog'
    | '/about/guestbook'
    | '/about/merch'
    | '/admin/artists'
    | '/admin/links'
    | '/admin/quality'
    | '/admin/quotes'
    | '/admin/reviews'
    | '/admin/wikidata'
    | '/artists/$slug'
    | '/blog/$id'
    | '/concerts/$slug'
    | '/editorial/images'
    | '/experience/media'
    | '/learn/gear'
    | '/learn/styles'
    | '/newsletter/$id'
    | '/newsletter/template'
    | '/quiz/archive'
    | '/reviews/$slug'
    | '/about'
    | '/admin'
    | '/artists'
    | '/blog'
    | '/concerts'
    | '/newsletter'
    | '/quiz'
    | '/reviews'
    | '/$locale/about/advertise'
    | '/$locale/artists/$slug'
    | '/about/merch/$slug'
    | '/admin/artists/$slug'
    | '/api/public/fourthwall-webhook'
    | '/quiz/cycle/$cycle'
    | '/$locale/artists'
    | '/about/merch/collection/$slug'
  id:
    | '__root__'
    | '/'
    | '/accessibility'
    | '/compare'
    | '/contact'
    | '/cookies'
    | '/copyright'
    | '/disclaimer'
    | '/festivals'
    | '/gallery'
    | '/gdpr'
    | '/guestbook'
    | '/history'
    | '/instruments'
    | '/listen'
    | '/login'
    | '/privacy'
    | '/radio'
    | '/sitemap.xml'
    | '/styles'
    | '/support'
    | '/terms'
    | '/updates'
    | '/watch'
    | '/worldmap'
    | '/about/advertise'
    | '/about/blog'
    | '/about/guestbook'
    | '/about/merch'
    | '/admin/artists'
    | '/admin/links'
    | '/admin/quality'
    | '/admin/quotes'
    | '/admin/reviews'
    | '/admin/wikidata'
    | '/artists/$slug'
    | '/blog/$id'
    | '/concerts/$slug'
    | '/editorial/images'
    | '/experience/media'
    | '/learn/gear'
    | '/learn/styles'
    | '/newsletter/$id'
    | '/newsletter/template'
    | '/quiz/archive'
    | '/reviews/$slug'
    | '/about/'
    | '/admin/'
    | '/artists/'
    | '/blog/'
    | '/concerts/'
    | '/newsletter/'
    | '/quiz/'
    | '/reviews/'
    | '/$locale/about/advertise'
    | '/$locale/artists/$slug'
    | '/about/merch/$slug'
    | '/admin/artists/$slug'
    | '/api/public/fourthwall-webhook'
    | '/quiz/cycle/$cycle'
    | '/$locale/artists/'
    | '/about/merch/collection/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilityRoute: typeof AccessibilityRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  CopyrightRoute: typeof CopyrightRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FestivalsRoute: typeof FestivalsRoute
  GalleryRoute: typeof GalleryRoute
  GdprRoute: typeof GdprRoute
  GuestbookRoute: typeof GuestbookRoute
  HistoryRoute: typeof HistoryRoute
  InstrumentsRoute: typeof InstrumentsRoute
  ListenRoute: typeof ListenRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RadioRoute: typeof RadioRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StylesRoute: typeof StylesRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  UpdatesRoute: typeof UpdatesRoute
  WatchRoute: typeof WatchRoute
  WorldmapRoute: typeof WorldmapRoute
  AboutAdvertiseRoute: typeof AboutAdvertiseRoute
  AboutBlogRoute: typeof AboutBlogRoute
  AboutGuestbookRoute: typeof AboutGuestbookRoute
  AboutMerchRoute: typeof AboutMerchRouteWithChildren
  AdminArtistsRoute: typeof AdminArtistsRouteWithChildren
  AdminLinksRoute: typeof AdminLinksRoute
  AdminQualityRoute: typeof AdminQualityRoute
  AdminQuotesRoute: typeof AdminQuotesRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminWikidataRoute: typeof AdminWikidataRoute
  ArtistsSlugRoute: typeof ArtistsSlugRoute
  BlogIdRoute: typeof BlogIdRoute
  ConcertsSlugRoute: typeof ConcertsSlugRoute
  EditorialImagesRoute: typeof EditorialImagesRoute
  ExperienceMediaRoute: typeof ExperienceMediaRoute
  LearnGearRoute: typeof LearnGearRoute
  LearnStylesRoute: typeof LearnStylesRoute
  NewsletterIdRoute: typeof NewsletterIdRoute
  NewsletterTemplateRoute: typeof NewsletterTemplateRoute
  QuizArchiveRoute: typeof QuizArchiveRoute
  ReviewsSlugRoute: typeof ReviewsSlugRoute
  AboutIndexRoute: typeof AboutIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ArtistsIndexRoute: typeof ArtistsIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ConcertsIndexRoute: typeof ConcertsIndexRoute
  NewsletterIndexRoute: typeof NewsletterIndexRoute
  QuizIndexRoute: typeof QuizIndexRoute
  ReviewsIndexRoute: typeof ReviewsIndexRoute
  LocaleAboutAdvertiseRoute: typeof LocaleAboutAdvertiseRoute
  LocaleArtistsSlugRoute: typeof LocaleArtistsSlugRoute
  ApiPublicFourthwallWebhookRoute: typeof ApiPublicFourthwallWebhookRoute
  QuizCycleCycleRoute: typeof QuizCycleCycleRoute
  LocaleArtistsIndexRoute: typeof LocaleArtistsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worldmap': {
      id: '/worldmap'
      path: '/worldmap'
      fullPath: '/worldmap'
      preLoaderRoute: typeof WorldmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styles': {
      id: '/styles'
      path: '/styles'
      fullPath: '/styles'
      preLoaderRoute: typeof StylesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio': {
      id: '/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listen': {
      id: '/listen'
      path: '/listen'
      fullPath: '/listen'
      preLoaderRoute: typeof ListenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instruments': {
      id: '/instruments'
      path: '/instruments'
      fullPath: '/instruments'
      preLoaderRoute: typeof InstrumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guestbook': {
      id: '/guestbook'
      path: '/guestbook'
      fullPath: '/guestbook'
      preLoaderRoute: typeof GuestbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdpr': {
      id: '/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof GdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festivals': {
      id: '/festivals'
      path: '/festivals'
      fullPath: '/festivals'
      preLoaderRoute: typeof FestivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copyright': {
      id: '/copyright'
      path: '/copyright'
      fullPath: '/copyright'
      preLoaderRoute: typeof CopyrightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/': {
      id: '/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof ReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/': {
      id: '/quiz/'
      path: '/quiz'
      fullPath: '/quiz/'
      preLoaderRoute: typeof QuizIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/': {
      id: '/newsletter/'
      path: '/newsletter'
      fullPath: '/newsletter/'
      preLoaderRoute: typeof NewsletterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concerts/': {
      id: '/concerts/'
      path: '/concerts'
      fullPath: '/concerts/'
      preLoaderRoute: typeof ConcertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/': {
      id: '/artists/'
      path: '/artists'
      fullPath: '/artists/'
      preLoaderRoute: typeof ArtistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/$slug': {
      id: '/reviews/$slug'
      path: '/reviews/$slug'
      fullPath: '/reviews/$slug'
      preLoaderRoute: typeof ReviewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/archive': {
      id: '/quiz/archive'
      path: '/quiz/archive'
      fullPath: '/quiz/archive'
      preLoaderRoute: typeof QuizArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/template': {
      id: '/newsletter/template'
      path: '/newsletter/template'
      fullPath: '/newsletter/template'
      preLoaderRoute: typeof NewsletterTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/$id': {
      id: '/newsletter/$id'
      path: '/newsletter/$id'
      fullPath: '/newsletter/$id'
      preLoaderRoute: typeof NewsletterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/styles': {
      id: '/learn/styles'
      path: '/learn/styles'
      fullPath: '/learn/styles'
      preLoaderRoute: typeof LearnStylesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/gear': {
      id: '/learn/gear'
      path: '/learn/gear'
      fullPath: '/learn/gear'
      preLoaderRoute: typeof LearnGearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/media': {
      id: '/experience/media'
      path: '/experience/media'
      fullPath: '/experience/media'
      preLoaderRoute: typeof ExperienceMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial/images': {
      id: '/editorial/images'
      path: '/editorial/images'
      fullPath: '/editorial/images'
      preLoaderRoute: typeof EditorialImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concerts/$slug': {
      id: '/concerts/$slug'
      path: '/concerts/$slug'
      fullPath: '/concerts/$slug'
      preLoaderRoute: typeof ConcertsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/blog/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$slug': {
      id: '/artists/$slug'
      path: '/artists/$slug'
      fullPath: '/artists/$slug'
      preLoaderRoute: typeof ArtistsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wikidata': {
      id: '/admin/wikidata'
      path: '/admin/wikidata'
      fullPath: '/admin/wikidata'
      preLoaderRoute: typeof AdminWikidataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/quotes': {
      id: '/admin/quotes'
      path: '/admin/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AdminQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/quality': {
      id: '/admin/quality'
      path: '/admin/quality'
      fullPath: '/admin/quality'
      preLoaderRoute: typeof AdminQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/links': {
      id: '/admin/links'
      path: '/admin/links'
      fullPath: '/admin/links'
      preLoaderRoute: typeof AdminLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/artists': {
      id: '/admin/artists'
      path: '/admin/artists'
      fullPath: '/admin/artists'
      preLoaderRoute: typeof AdminArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/merch': {
      id: '/about/merch'
      path: '/about/merch'
      fullPath: '/about/merch'
      preLoaderRoute: typeof AboutMerchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/guestbook': {
      id: '/about/guestbook'
      path: '/about/guestbook'
      fullPath: '/about/guestbook'
      preLoaderRoute: typeof AboutGuestbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/blog': {
      id: '/about/blog'
      path: '/about/blog'
      fullPath: '/about/blog'
      preLoaderRoute: typeof AboutBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/advertise': {
      id: '/about/advertise'
      path: '/about/advertise'
      fullPath: '/about/advertise'
      preLoaderRoute: typeof AboutAdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/artists/': {
      id: '/$locale/artists/'
      path: '/$locale/artists'
      fullPath: '/$locale/artists/'
      preLoaderRoute: typeof LocaleArtistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/cycle/$cycle': {
      id: '/quiz/cycle/$cycle'
      path: '/quiz/cycle/$cycle'
      fullPath: '/quiz/cycle/$cycle'
      preLoaderRoute: typeof QuizCycleCycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fourthwall-webhook': {
      id: '/api/public/fourthwall-webhook'
      path: '/api/public/fourthwall-webhook'
      fullPath: '/api/public/fourthwall-webhook'
      preLoaderRoute: typeof ApiPublicFourthwallWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/artists/$slug': {
      id: '/admin/artists/$slug'
      path: '/$slug'
      fullPath: '/admin/artists/$slug'
      preLoaderRoute: typeof AdminArtistsSlugRouteImport
      parentRoute: typeof AdminArtistsRoute
    }
    '/about/merch/$slug': {
      id: '/about/merch/$slug'
      path: '/$slug'
      fullPath: '/about/merch/$slug'
      preLoaderRoute: typeof AboutMerchSlugRouteImport
      parentRoute: typeof AboutMerchRoute
    }
    '/$locale/artists/$slug': {
      id: '/$locale/artists/$slug'
      path: '/$locale/artists/$slug'
      fullPath: '/$locale/artists/$slug'
      preLoaderRoute: typeof LocaleArtistsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/about/advertise': {
      id: '/$locale/about/advertise'
      path: '/$locale/about/advertise'
      fullPath: '/$locale/about/advertise'
      preLoaderRoute: typeof LocaleAboutAdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/merch/collection/$slug': {
      id: '/about/merch/collection/$slug'
      path: '/collection/$slug'
      fullPath: '/about/merch/collection/$slug'
      preLoaderRoute: typeof AboutMerchCollectionSlugRouteImport
      parentRoute: typeof AboutMerchRoute
    }
  }
}

interface AboutMerchRouteChildren {
  AboutMerchSlugRoute: typeof AboutMerchSlugRoute
  AboutMerchCollectionSlugRoute: typeof AboutMerchCollectionSlugRoute
}

const AboutMerchRouteChildren: AboutMerchRouteChildren = {
  AboutMerchSlugRoute: AboutMerchSlugRoute,
  AboutMerchCollectionSlugRoute: AboutMerchCollectionSlugRoute,
}

const AboutMerchRouteWithChildren = AboutMerchRoute._addFileChildren(
  AboutMerchRouteChildren,
)

interface AdminArtistsRouteChildren {
  AdminArtistsSlugRoute: typeof AdminArtistsSlugRoute
}

const AdminArtistsRouteChildren: AdminArtistsRouteChildren = {
  AdminArtistsSlugRoute: AdminArtistsSlugRoute,
}

const AdminArtistsRouteWithChildren = AdminArtistsRoute._addFileChildren(
  AdminArtistsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilityRoute: AccessibilityRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  CopyrightRoute: CopyrightRoute,
  DisclaimerRoute: DisclaimerRoute,
  FestivalsRoute: FestivalsRoute,
  GalleryRoute: GalleryRoute,
  GdprRoute: GdprRoute,
  GuestbookRoute: GuestbookRoute,
  HistoryRoute: HistoryRoute,
  InstrumentsRoute: InstrumentsRoute,
  ListenRoute: ListenRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RadioRoute: RadioRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StylesRoute: StylesRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  UpdatesRoute: UpdatesRoute,
  WatchRoute: WatchRoute,
  WorldmapRoute: WorldmapRoute,
  AboutAdvertiseRoute: AboutAdvertiseRoute,
  AboutBlogRoute: AboutBlogRoute,
  AboutGuestbookRoute: AboutGuestbookRoute,
  AboutMerchRoute: AboutMerchRouteWithChildren,
  AdminArtistsRoute: AdminArtistsRouteWithChildren,
  AdminLinksRoute: AdminLinksRoute,
  AdminQualityRoute: AdminQualityRoute,
  AdminQuotesRoute: AdminQuotesRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminWikidataRoute: AdminWikidataRoute,
  ArtistsSlugRoute: ArtistsSlugRoute,
  BlogIdRoute: BlogIdRoute,
  ConcertsSlugRoute: ConcertsSlugRoute,
  EditorialImagesRoute: EditorialImagesRoute,
  ExperienceMediaRoute: ExperienceMediaRoute,
  LearnGearRoute: LearnGearRoute,
  LearnStylesRoute: LearnStylesRoute,
  NewsletterIdRoute: NewsletterIdRoute,
  NewsletterTemplateRoute: NewsletterTemplateRoute,
  QuizArchiveRoute: QuizArchiveRoute,
  ReviewsSlugRoute: ReviewsSlugRoute,
  AboutIndexRoute: AboutIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  ArtistsIndexRoute: ArtistsIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ConcertsIndexRoute: ConcertsIndexRoute,
  NewsletterIndexRoute: NewsletterIndexRoute,
  QuizIndexRoute: QuizIndexRoute,
  ReviewsIndexRoute: ReviewsIndexRoute,
  LocaleAboutAdvertiseRoute: LocaleAboutAdvertiseRoute,
  LocaleArtistsSlugRoute: LocaleArtistsSlugRoute,
  ApiPublicFourthwallWebhookRoute: ApiPublicFourthwallWebhookRoute,
  QuizCycleCycleRoute: QuizCycleCycleRoute,
  LocaleArtistsIndexRoute: LocaleArtistsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
