ALTER TABLE public.artists
  ADD COLUMN IF NOT EXISTS short_de text,
  ADD COLUMN IF NOT EXISTS short_pl text,
  ADD COLUMN IF NOT EXISTS biography_pl text,
  ADD COLUMN IF NOT EXISTS influence_de text,
  ADD COLUMN IF NOT EXISTS influence_pl text,
  ADD COLUMN IF NOT EXISTS era_label_de text,
  ADD COLUMN IF NOT EXISTS era_label_pl text,
  ADD COLUMN IF NOT EXISTS seo_title_de text,
  ADD COLUMN IF NOT EXISTS seo_title_pl text,
  ADD COLUMN IF NOT EXISTS seo_description_de text,
  ADD COLUMN IF NOT EXISTS seo_description_pl text,
  ADD COLUMN IF NOT EXISTS signature_songs_en text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS signature_songs_no text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS signature_songs_sv text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS signature_songs_de text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS signature_songs_pl text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS influences_en text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS influences_no text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS influences_sv text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS influences_de text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS influences_pl text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS family_sv jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS family_de jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS family_pl jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS formative_sv jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS formative_pl jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS anecdotes_sv jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS anecdotes_de jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS anecdotes_pl jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS instruments_no jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS instruments_sv jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS instruments_de jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS instruments_pl jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS collaborators_no jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS collaborators_sv jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS collaborators_de jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS collaborators_pl jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS discography_en jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS discography_no jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS discography_sv jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS discography_de jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS discography_pl jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS awards_en jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS awards_no jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS awards_sv jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS awards_de jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS awards_pl jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS press_quotes_en jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS press_quotes_no jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS press_quotes_sv jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS press_quotes_de jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS press_quotes_pl jsonb NOT NULL DEFAULT '[]'::jsonb;