// Auto-generated by scripts/fetch_gallery_extras.ts. Do not edit by hand.
export type GalleryPhoto = {
  src: string;
  alt: string;
  caption: string;
  credit: string;
  creditUrl: string;
  source: "Unsplash" | "Pexels" | "Pixabay";
};

export type GallerySection = {
  id: string;
  titleEn: string;
  leadEn: string;
  photos: GalleryPhoto[];
};

export const GALLERY_EXTRAS: GallerySection[] = [
  {
    "id": "electric-era",
    "titleEn": "The Electric Era",
    "leadEn": "From Chicago juke joints to amplified stages — the sound that changed everything.",
    "photos": [
      {
        "src": "https://images.pexels.com/photos/34679991/pexels-photo-34679991.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "alt": "Neon-lit vintage clothing store 'Chicago' in bustling Tokyo street at night.",
        "caption": "Neon-lit vintage clothing store 'Chicago' in bustling Tokyo street at night.",
        "credit": "Memory Lane",
        "creditUrl": "https://www.pexels.com/@memory-lane-2157293172",
        "source": "Pexels"
      },
      {
        "src": "https://images.pexels.com/photos/13637680/pexels-photo-13637680.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "alt": "Chicago Theatre marquee in downtown, showcasing architectural beauty and urban life.",
        "caption": "Chicago Theatre marquee in downtown, showcasing architectural beauty and urban life.",
        "credit": "Rubi Murillo Cruz",
        "creditUrl": "https://www.pexels.com/@rubi-murillo-cruz-300282745",
        "source": "Pexels"
      },
      {
        "src": "https://images.pexels.com/photos/9419381/pexels-photo-9419381.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "alt": "Atmospheric jazz club scene with a man smoking and performers on stage under dim lighting.",
        "caption": "Atmospheric jazz club scene with a man smoking and performers on stage under dim lighting.",
        "credit": "cottonbro studio",
        "creditUrl": "https://www.pexels.com/@cottonbro",
        "source": "Pexels"
      },
      {
        "src": "https://images.pexels.com/photos/9008844/pexels-photo-9008844.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "alt": "A male singer passionately performs on stage, holding a vintage microphone.",
        "caption": "A male singer passionately performs on stage, holding a vintage microphone.",
        "credit": "Yan Krukau",
        "creditUrl": "https://www.pexels.com/@yankrukov",
        "source": "Pexels"
      },
      {
        "src": "https://images.pexels.com/photos/8043766/pexels-photo-8043766.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "alt": "A passionate male singer performing with a vintage microphone, expressing deep emotions on stage.",
        "caption": "A passionate male singer performing with a vintage microphone, expressing deep emotions on stage.",
        "credit": "AI25.Studio  AI GENERATIVE",
        "creditUrl": "https://www.pexels.com/@ai25studio",
        "source": "Pexels"
      },
      {
        "src": "https://images.pexels.com/photos/16951967/pexels-photo-16951967.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "alt": "Iconic Chicago Theater on a bustling street, showcasing vintage architecture and vibrant city life.",
        "caption": "Iconic Chicago Theater on a bustling street, showcasing vintage architecture and vibrant city life.",
        "credit": "Chris Duan",
        "creditUrl": "https://www.pexels.com/@chris-duan-259139750",
        "source": "Pexels"
      },
      {
        "src": "https://images.pexels.com/photos/14635970/pexels-photo-14635970.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "alt": "Monochrome image of a fire escape on a brick wall with Chicago Theater text.",
        "caption": "Monochrome image of a fire escape on a brick wall with Chicago Theater text.",
        "credit": "Dom Sch-veg-man",
        "creditUrl": "https://www.pexels.com/@dom-sch-veg-man-381944029",
        "source": "Pexels"
      },
      {
        "src": "https://images.pexels.com/photos/8043753/pexels-photo-8043753.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "alt": "Stylish jazz singer in a hat performing under blue stage lights with a vintage microphone.",
        "caption": "Stylish jazz singer in a hat performing under blue stage lights with a vintage microphone.",
        "credit": "AI25.Studio  AI GENERATIVE",
        "creditUrl": "https://www.pexels.com/@ai25studio",
        "source": "Pexels"
      }
    ]
  },
  {
    "id": "guitars-and-gear",
    "titleEn": "Blues Guitars & Gear",
    "leadEn": "The instruments that gave the blues its voice.",
    "photos": [
      {
        "src": "https://images.pexels.com/photos/3755771/pexels-photo-3755771.png?auto=compress&cs=tinysrgb&h=650&w=940",
        "alt": "Detailed shot of an electric guitar with a dark background emphasizing the instrument's features.",
        "caption": "Detailed shot of an electric guitar with a dark background emphasizing the instrument's features.",
        "credit": "Andre Moura",
        "creditUrl": "https://www.pexels.com/@oandremoura",
        "source": "Pexels"
      },
      {
        "src": "https://images.pexels.com/photos/12061203/pexels-photo-12061203.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "alt": "Detailed close-up of an electric guitar highlighting its strings and body.",
        "caption": "Detailed close-up of an electric guitar highlighting its strings and body.",
        "credit": "Konna Jpg",
        "creditUrl": "https://www.pexels.com/@konna-jpg-161731893",
        "source": "Pexels"
      },
      {
        "src": "https://images.pexels.com/photos/9516822/pexels-photo-9516822.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "alt": "Detailed close-up of an electric guitar's headstock showcasing its strings and tuning pegs.",
        "caption": "Detailed close-up of an electric guitar's headstock showcasing its strings and tuning pegs.",
        "credit": "iram shehzad",
        "creditUrl": "https://www.pexels.com/@iram-shehzad-45081404",
        "source": "Pexels"
      },
      {
        "src": "https://images.pexels.com/photos/30888306/pexels-photo-30888306.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "alt": "Detailed close-up of a cream Stratocaster electric guitar highlighting strings and body.",
        "caption": "Detailed close-up of a cream Stratocaster electric guitar highlighting strings and body.",
        "credit": "alexey",
        "creditUrl": "https://www.pexels.com/@alexey-278505875",
        "source": "Pexels"
      },
      {
        "src": "https://images.pexels.com/photos/1589280/pexels-photo-1589280.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "alt": "A focused view of a classic electric guitar's body and strings inside its case.",
        "caption": "A focused view of a classic electric guitar's body and strings inside its case.",
        "credit": "Rene Terp",
        "creditUrl": "https://www.pexels.com/@reneterp",
        "source": "Pexels"
      },
      {
        "src": "https://images.pexels.com/photos/1047796/pexels-photo-1047796.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "alt": "Ambient close-up of an electric guitar's bridge illuminated by sunset light through a window.",
        "caption": "Ambient close-up of an electric guitar's bridge illuminated by sunset light through a window.",
        "credit": "Ruslan Alekso",
        "creditUrl": "https://www.pexels.com/@oskelaq",
        "source": "Pexels"
      }
    ]
  },
  {
    "id": "nordic-blues",
    "titleEn": "Nordic Blues",
    "leadEn": "The Scandinavian scene — festivals, clubs, and the long winter sound.",
    "photos": [
      {
        "src": "https://images.pexels.com/photos/2417730/pexels-photo-2417730.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "alt": "A vibrant concert scene with a crowd surfer and lively audience members enjoying a live performance.",
        "caption": "A vibrant concert scene with a crowd surfer and lively audience members enjoying a live performance.",
        "credit": "Johannes Havn",
        "creditUrl": "https://www.pexels.com/@johannes-havn-835931",
        "source": "Pexels"
      },
      {
        "src": "https://images.pexels.com/photos/1755087/pexels-photo-1755087.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "alt": "Energetic concert crowd enjoying a nighttime performance in Helsinki with vibrant lights and performers.",
        "caption": "Energetic concert crowd enjoying a nighttime performance in Helsinki with vibrant lights and performers.",
        "credit": "Ingo Joseph",
        "creditUrl": "https://www.pexels.com/@ingo",
        "source": "Pexels"
      },
      {
        "src": "https://images.pexels.com/photos/32802231/pexels-photo-32802231.png?auto=compress&cs=tinysrgb&h=650&w=940",
        "alt": "Large crowd at an outdoor music festival with tents and blue skies.",
        "caption": "Large crowd at an outdoor music festival with tents and blue skies.",
        "credit": "Dua'a Al-Amad",
        "creditUrl": "https://www.pexels.com/@duawalidd",
        "source": "Pexels"
      },
      {
        "src": "https://images.pexels.com/photos/14364672/pexels-photo-14364672.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "alt": "Vibrant image of a trumpeter playing during a live jazz concert, capturing the essence of musical performance.",
        "caption": "Vibrant image of a trumpeter playing during a live jazz concert, capturing the essence of musical performance.",
        "credit": "Caleb Oquendo",
        "creditUrl": "https://www.pexels.com/@caleboquendo",
        "source": "Pexels"
      },
      {
        "src": "https://images.pexels.com/photos/4218027/pexels-photo-4218027.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "alt": "Energetic live music concert featuring performers on a vibrant stage, captivating a large audience.",
        "caption": "Energetic live music concert featuring performers on a vibrant stage, captivating a large audience.",
        "credit": "george charry",
        "creditUrl": "https://www.pexels.com/@george-charry-2643329",
        "source": "Pexels"
      },
      {
        "src": "https://images.pexels.com/photos/33694616/pexels-photo-33694616.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
        "alt": "Close-up of a female guitarist playing an electric guitar on stage during a live concert.",
        "caption": "Close-up of a female guitarist playing an electric guitar on stage during a live concert.",
        "credit": "Zozi Molina",
        "creditUrl": "https://www.pexels.com/@zozi-molina-497046090",
        "source": "Pexels"
      }
    ]
  }
];
